import Head from "next/head";
import Image from "next/image";
import { ThemeProvider, createTheme } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import Footer from "@/components/Footer";
import Slogan from "@/sections/Slogan";
import Branches from "@/sections/Branches";
import Service from "@/sections/Service";
import Services from "@/sections/Services";
import Carousel from "@/components/Carousel";
import Hero from "@/sections/Hero";
import CurrencyExchanger from "@/components/CurrencyExchanger";
import India from "../assets/Property 1=India.png";

export default function Home() {
  const theme = createTheme({
    typography: {
      fontFamily: "Mulish, sans-serif",
      button: {
        textTransform: "none",
      },
    },
  });

  return (
    <>
      <Head>
        <title>Unimoni Webflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        {/* <Hero />
        <Service />
        <Services />
        <Branches />
        <Slogan />
        <Footer /> */}
        <CurrencyExchanger flagSvg={India} currency={""} code={""} />
      </ThemeProvider>
    </>
  );
}
