import Head from "next/head";
import Image from "next/image";
import Service from "../sections/service";
import Branches from "../sections/branches";
import Slogan from "../sections/slogan";
import Footer from "@/components/footer";
import Services from "../sections/services";
import { ThemeProvider, createTheme } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import '@fontsource/mulish/400.css';


export default function Home() {

  const theme = createTheme({
    typography: {
      fontFamily: "Mulish, sans-serif"
    },
  });

  return (
    <>
      <Head>
        <title>Unimoni Webflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Service />
        {/* <Services /> */}
        <Branches />
        <Slogan />
        <Footer />
      </ThemeProvider>
    </>
  );
}
